# ai_player.gd
extends CharacterBody2D

## --- Configuration ---
# File paths for communication with the Python AI script
# Keeping hardcoded paths as requested
var game_state_file = "C://Users//LOQ//Documents//AI RUNNER//AI_data//game_state.json"
var action_file = "C://Users//LOQ//Documents//AI RUNNER//AI_data//ai_action.json"
var ai_data_dir = "C://Users//LOQ//Documents//AI RUNNER//AI_data" # Directory to ensure exists
# Temporary file path using the hardcoded directory
var game_state_temp_file = "C://Users//LOQ//Documents//AI RUNNER//AI_data//game_state.json.tmp"

## --- Movement Parameters ---
const SPEED = 130.0
const JUMP_VELOCITY = -300.0
const ACCELERATION = 600.0 # Use float for consistency
const FRICTION = 800.0     # Use float for consistency

## --- Physics ---
var gravity = ProjectSettings.get_setting("physics/2d/default_gravity")

## --- Game State & RL ---
const DEATH_Y = 1000  # Y-coordinate below which the player respawns
# --- REMOVED Hardcoded start position variable ---
# var start_position = Vector2(32, 33) # Initial position to respawn at

# --- ADDED dynamic start position variable ---
var initial_start_position: Vector2 # Store the position from the editor

# Define Rewards/Penalties (Adjust these values based on training)
const COIN_REWARD = 25.0       # Reward for collecting a coin
const WALL_PENALTY = -1.0      # Penalty for hitting a wall/obstacle
const FALL_PENALTY = -50.0     # Large penalty for falling off
const STEP_PENALTY = -0.1      # Small penalty per step to encourage efficiency
# const GOAL_REWARD = 100.0    # Optional: Reward for reaching a goal

# Variables to store per-step results for RL
var current_step_reward = 0.0
var episode_done = false


# --- Initialization ---
func _ready():
	# --- Store the initial position set in the editor ---
	initial_start_position = global_position
	print("AI Player initial position set to: ", initial_start_position)

	ensure_ai_data_folder_exists()
	# Set initial position (useful if placed in the editor elsewhere) - Not needed, editor sets it.
	# global_position = initial_start_position # Already at initial position

	# Add the player to a group for easy lookup by other nodes if needed
	add_to_group("AIPlayer")
	# Connect the signal if the player has an Area2D for coin detection
	if has_node("PickupArea"):
		$PickupArea.area_entered.connect(_on_pickup_area_entered)
	else:
		print("⚠️ WARNING: No 'PickupArea' node found on AIPlayer. Coin collection via Area2D signal disabled.")


# --- Core Logic Loop ---
func _physics_process(delta):
	# --- Reset Per-Step RL Variables ---
	current_step_reward = 0.0
	episode_done = false

	# --- Check for Death Condition ---
	if global_position.y > DEATH_Y:
		print("💀 AI Player fell! Respawning.")
		current_step_reward += FALL_PENALTY # Apply penalty for falling
		episode_done = true          # Signal that the episode ended
		respawn()
		# Save state immediately after respawn to send the 'done' signal and final penalty
		save_game_state()
		return # Stop further processing this frame after respawn

	# --- Apply Basic Living Penalty ---
	current_step_reward += STEP_PENALTY

	# --- Apply Gravity ---
	if not is_on_floor():
		velocity.y += gravity * delta

	# --- Get AI Action ---
	var action = read_ai_action()

	# --- Handle Horizontal Movement ---
	var target_velocity_x = 0
	if action == "left":
		target_velocity_x = -SPEED
	elif action == "right":
		target_velocity_x = SPEED

	# Apply acceleration/friction
	if target_velocity_x != 0:
		velocity.x = move_toward(velocity.x, target_velocity_x, ACCELERATION * delta)
	else:
		velocity.x = move_toward(velocity.x, 0, FRICTION * delta)

	# --- Handle Jumping ---
	if action == "jump" and is_on_floor():
		velocity.y = JUMP_VELOCITY

	# --- Execute Movement & Collision ---
	move_and_slide()

	# --- Calculate Rewards/Penalties *After* Movement ---
	# Check for wall collisions resulting from the move
	if get_slide_collision_count() > 0:
		current_step_reward += WALL_PENALTY

	# --- Optional: Check for Goal Condition ---
	# if player_reached_goal:
	#    current_step_reward += GOAL_REWARD
	#    episode_done = true

	# --- Save Game State for AI ---
	save_game_state()


# --- Helper Functions ---

func respawn():
	"""Resets the player's position and velocity to the initial start position."""
	# --- Use the stored initial position ---
	global_position = initial_start_position
	velocity = Vector2.ZERO


func read_ai_action():
	"""Reads the action string from the JSON file generated by the Python AI."""
	if not FileAccess.file_exists(action_file):
		return "idle"
	var file = FileAccess.open(action_file, FileAccess.READ)
	if file == null:
		print("❌ Error opening action file:", FileAccess.get_open_error())
		return "idle"
	var content = file.get_as_text()
	file.close()
	if content.is_empty():
		return "idle"
	var parse_result = JSON.parse_string(content)
	if parse_result == null:
		print("❌ Error parsing action JSON content.")
		return "idle"
	if typeof(parse_result) != TYPE_DICTIONARY or not parse_result.has("action"):
		print("⚠️ Action JSON format incorrect, defaulting to 'idle'. Content:", content)
		return "idle"
	return parse_result["action"]


func save_game_state():
	"""Gathers current state information and saves it atomically to the JSON file."""
	# --- Gather State Data ---
	var vision_grid = []
	var vision_node = get_tree().get_first_node_in_group("VisionGrid")
	if vision_node != null and vision_node.has_method("get_vision_grid"):
		vision_grid = vision_node.get_vision_grid()
		if vision_grid.is_empty() or vision_grid[0].size() != 16 or vision_grid.size() != 22:
			print("❌ ERROR in ai_player: Received invalid vision grid size!")
			vision_grid = []; for y in range(22): var row = []; for x in range(16): row.append(0); vision_grid.append(row)
	else:
		print("❌ ERROR: VisionGrid node not found or has no get_vision_grid method!")
		vision_grid = []; for y in range(22): var row = []; for x in range(16): row.append(0); vision_grid.append(row)
	var state = {
		"player_x": global_position.x, "player_y": global_position.y,
		"velocity_x": velocity.x, "velocity_y": velocity.y,
		"vision_grid": vision_grid, "reward": current_step_reward, "done": episode_done
	}
	# --- Atomic Write Process ---
	ensure_ai_data_folder_exists()
	var file = FileAccess.open(game_state_temp_file, FileAccess.WRITE)
	if file != null:
		file.store_string(JSON.stringify(state, "\t"))
		file.close()
		# --- Use absolute path for DirAccess.open if needed, though base dir should work ---
		var dir = DirAccess.open(ai_data_dir.get_base_dir()) # Try getting base dir from path
		if dir == null:
			print("❌ Error opening base directory for rename. Path: %s Code: %s" % [ai_data_dir.get_base_dir(), DirAccess.get_open_error()])
			 # Fallback attempt if base_dir fails or is not what's needed
			dir = DirAccess.open("C://") # Open C drive directly - LESS SAFE
			if dir == null:
				print("❌ Error opening C:// directory for rename. Code: %s" % DirAccess.get_open_error())
				return # Cannot proceed

		# Construct full paths for rename relative to the opened directory 'dir'
		# This part is tricky with absolute paths, rename often expects paths relative to the DirAccess handle
		# Let's assume rename works with full paths directly for now, though GDScript docs are sparse here.
		var rename_error = dir.rename(game_state_temp_file, game_state_file)
		if rename_error != OK:
			print("❌ Error renaming temp game state file: %s -> %s. Code: %s" % [game_state_temp_file, game_state_file, rename_error])
			var remove_error = dir.remove(game_state_temp_file); if remove_error != OK: print("❌ Additionally, failed to remove leftover temp file: %s. Code: %s" % [game_state_temp_file, remove_error])
	else: print("❌ Error opening temporary game state file for writing: %s. Code: %s" % [game_state_temp_file, FileAccess.get_open_error()])


func ensure_ai_data_folder_exists():
	"""Checks if the AI_data directory exists and creates it if not (using absolute path)."""
	# Need DirAccess relative to the path we want to check/create
	var base_dir_path = ai_data_dir.get_base_dir() # e.g., "C://Users//LOQ//Documents//AI RUNNER"
	var folder_name = ai_data_dir.get_file()       # e.g., "AI_data"

	var dir = DirAccess.open(base_dir_path)
	if dir == null:
		print("❌ CRITICAL Error opening base directory: %s. Cannot ensure AI_data folder exists. Code: %s" % [base_dir_path, DirAccess.get_open_error()])
		return # Cannot proceed

	if not dir.dir_exists(folder_name):
		print("📂 AI_data directory not found in %s. Creating..." % base_dir_path)
		var err = dir.make_dir(folder_name) # Create folder relative to handle
		if err != OK:
			print("❌ Error creating directory '%s' inside '%s'. Code: %s" % [folder_name, base_dir_path, err])
		# else: # Optional: Success message
			# print("✅ Directory '%s' created successfully." % ai_data_dir)


func _on_pickup_area_entered(area):
	"""Handles collision with areas, specifically looking for coins."""
	if area.is_in_group("Coins"):
		print("💰 AI Coin collected!")
		current_step_reward += COIN_REWARD # Add reward for collecting the coin
		area.queue_free() # Remove the collected coin from the scene
